config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios

  get 'login/index'

  root 'login#index'

  resources :prospectos
  resources :historicoprospectos
  
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route(maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/estado.rb
class Estado < ActiveRecord::Base
	has_many :prospectos
end

app/models/historicoprospecto.rb
class Historicoprospecto < ActiveRecord::Base
	belongs_to :situacao
	belongs_to :prospecto
end

app/models/prospecto.rb
class Prospecto < ActiveRecord::Base
  validates_presence_of :nome
  belongs_to :estado
  has_many :historicoprospectos
  
  VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}
  validates_format_of :telefone, :with =>  /\d[0-9]\)*\z/

  has_attached_file :anexo
  validates_attachment_content_type :anexo, :content_type => ['image/jpg','image/jpeg','image/pjpeg','image/png',
  		'image/x-png','image/gif','application/pdf','application/msword', 
  		'application/vnd.openxmlformats-officedocument.wordprocessingml.document']
end

app/models/situacao.rb
class Situacao < ActiveRecord::Base
	has_many :historicoprospectos
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :nome
    devise_parameter_sanitizer.for(:sign_up) << :funcao
  end
end

app/controllers/historicoprospectos_controller.rb
class HistoricoprospectosController < ApplicationController
  before_action :authenticate_usuario!

  def index
    @historicoprospectos = Historicoprospecto.all
  end

  def new
    @historicoprospecto = Historicoprospecto.new
  end

  def create
    @historicoprospecto = Historicoprospecto.new(user_params)

    if @historicoprospecto.save
      redirect_to new_prospecto_path
    else
      render 'new'  
    end
  end

  private
  
  def user_params
    params.require(:historicoprospecto).permit(:descricao, :situacao_id, :anexo)
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_action :authenticate_usuario!
  def index
  	
  end
end

app/controllers/prospectos_controller.rb
class ProspectosController < ApplicationController
  before_action :authenticate_usuario!

  respond_to :pdf
  def index
    @prospectos = Prospecto.all
  end

  def show
    @prospecto = Prospecto.find(params[:id])
  end

  def new
    @prospecto = Prospecto.new
  end

  def create
    @prospecto = Prospecto.new(user_params)

    if @prospecto.save
      redirect_to new_prospecto_path, notice: t('notice.created', model:@prospecto.model_name) 
    else
      @prospectos = Prospecto.where(situacao_id: params[:busca].to_i)

      render :pdf => "Prospectos", :template => 'prospectos/index.pdf.erb'
    end
  end

  def edit
    @prospecto = Prospecto.find(params[:id])
  end

  def update
    @prospecto = Prospecto.find(params[:id])

    if @prospecto.update_attributes(user_params)
      redirect_to prospectos_path, notice: t('notice.update', model:@prospecto.model_name) 
    else
      render 'edit'
    end
  end

  def destroy
    @prospecto = Prospecto.find(params[:id])
    @prospecto.destroy
    redirect_to prospectos_path, notice: t('notice.delete', model:@prospecto.model_name) 
  end

  private
  
  def user_params
    params.require(:prospecto).permit(:nome, :empresa, :telefone, :email, :cidade, :estado_id, 
      :social, :situacao_id, :descricao, :anexo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/historicoprospectos_helper.rb
module HistoricoprospectosHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/prospectos_helper.rb
module ProspectosHelper
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-Br" data-ng-app="demo" ng-data-cloak>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Projeto" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body> 
    <div class="row">
      <div class="col-lg-12">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/login/index.html.erb
<!--<% if usuario_signed_in? %>
<ul>
	<li><%= link_to "Sair", destroy_usuario_session_path, method: :delete  %></li>
</ul>
<% else %>
<ul>
	<li><%= link_to "Logar", new_usuario_session_path %></li>
	<li><%= link_to "CADASTRO", new_usuario_registration_path %></li>
</ul> 
<% end %>
<ul>
	<li><%= link_to "Prospecto", new_prospecto_path %></li>
</ul>
-->
    
<body style="background-color:#6d6d6d">
  <div class="linhaVertical"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
		    <div id="centralizarMenu"><span style="font-size: 30px;"></span></br> <%= link_to "Prospecto", new_prospecto_path, :style=> 'color:#7ef297' %></div>
      </div>
    </div>
  </div>
</body>

app/views/prospectos/_cadastroBasico.html.erb
<div ng-app="demo">
  <div ng-controller="ControllerCadastroBasico">

      <%= form_for @prospecto, :html => { :class => "form-horizontal prospecto" } do |f| %>
      <div class="container">
        <div ng-hide="esconderCadastroBasico"> 
          <div class="control-group">
            <div class="controls">
              <div class="col-xs-10"><%= f.text_field :nome, :class => 'form-control', :placeholder => "Nome" %></div>
              </div>
          </div></br></br>

          <div class="control-group">
            <div class="controls">
              <div class="col-xs-10"><%= f.text_field :empresa, :class => 'form-control', :placeholder => "Empresa" %></div>
            </div>
          </div></br></br>

          <div class="control-group">
            <div class="controls">
              <div class="col-xs-10"><%= f.text_field :email, :class => 'form-control', :placeholder => "Email" %></div>
            </div>
          </div></br></br>

          <div class="control-group">
            <div class="controls">
              <div class="col-xs-10"><%= f.text_field :telefone, :class => 'form-control', :placeholder => "Telefone" %></div>            
            </div>
          </div></br></br>

          <div class="control-group">
            <div class="controls">
              <div class="col-xs-6" style="padding-right:5px;"><%= f.text_field :cidade, :class => 'form-control', :placeholder => "Cidade" %></div>     

              <div class="col-xs-4" style="padding-left:5px;"><%= f.collection_select :estado_id, Estado.all, :id, :UF, {prompt: "UF"}, {class: "form-control"} %></div> 
            </div>
          </div></br></br></br>

          <p style="color:#a39d95">COMO CHEGOU ATÉ A NEO/SAGA?</p>

            <a style="background-color: #133783;" ng-click="selecionarIconesSocialFacebook = true" ng-show="!selecionarIconesSocialFacebook" class="btn btn-social-icon btn-facebook espacamentoPequenoIconesSociais">
              <i class="fa fa-facebook"></i>
              <p class="alinharDescricaoIconesSociais">Facebook</p>
            </a> 
            <a ng-click="selecionarIconesSocialFacebook = false" ng-show="selecionarIconesSocialFacebook" class="btn btn-social-icon btn-facebook espacamentoPequenoIconesSociais">
              <i class="fa fa-facebook"></i>
              <p class="alinharDescricaoIconesSociais">Facebook</p>
            </a>
            
            <a style="background-color: #133783;" ng-click="selecionarIconesSocialInstagram = true" ng-show="!selecionarIconesSocialInstagram" class="btn btn-social-icon btn-instagram espacamentoPequenoIconesSociais">
              <i class="fa fa-instagram"></i>
              <p class="alinharDescricaoIconesSociais">Instagram</p>
            </a> 
            <a ng-click="selecionarIconesSocialInstagram = false" ng-show="selecionarIconesSocialInstagram" class="btn btn-social-icon btn-instagram espacamentoPequenoIconesSociais">
              <i class="fa fa-instagram"></i>
              <p class="alinharDescricaoIconesSociais">Instagram</p>
            </a>

            <a style="background-color: #1791E3;"  ng-click="selecionarIconesSocialSkype = true" ng-show="!selecionarIconesSocialSkype" class="btn btn-social-icon btn-skype espacamentoGrandeIconesSociais">
              <i class="fa fa-skype"></i>
              <p class="alinharDescricaoIconesSociais">Skype</p>
            </a> 
            <a ng-click="selecionarIconesSocialSkype = false" ng-show="selecionarIconesSocialSkype" class="btn btn-social-icon btn-skype espacamentoGrandeIconesSociais">
              <i class="fa fa-skype"></i>
              <p class="alinharDescricaoIconesSociais">Skype</p>
            </a> 

            <a style="background-color: #751015;"  ng-click="selecionarIconesSocialYoutube = true" ng-show="!selecionarIconesSocialYoutube" class="btn btn-social-icon btn-youtube espacamentoMedioIconesSociais">
              <i class="fa fa-youtube"></i>
               <p class="alinharDescricaoIconesSociais">Youtube</p>
            </a> 
            <a ng-click="selecionarIconesSocialYoutube = false" ng-show="selecionarIconesSocialYoutube" class="btn btn-social-icon btn-youtube espacamentoMedioIconesSociais">
              <i class="fa fa-youtube"></i>
              <p class="alinharDescricaoIconesSociais">Youtube</p>
            </a> 

            <a style="background-color: #1791E3" ng-click="selecionarIconesSocialLinkedin = true" ng-show="!selecionarIconesSocialLinkedin" class="btn btn-social-icon btn-linkedin espacamentoMedioIconesSociais">
              <i class="fa fa-linkedin"></i>
              <p class="alinharDescricaoIconesSociais"> Linkedin</p>
            </a> 
            <a ng-click="selecionarIconesSocialLinkedin = false" ng-show="selecionarIconesSocialLinkedin" class="btn btn-social-icon btn-linkedin espacamentoMedioIconesSociais">
              <i class="fa fa-linkedin"></i>
              <p class="alinharDescricaoIconesSociais"> Linkedin</p>
            </a> 
            
            <%= f.submit "Salvar", :class => 'btn btn-primary botaoSalvar'  %>
        
          <span ng-if="!selecionarIconesSocialInstagram">
            <% valor = "Instagram" %>
            <%= f.text_field :social, :value => valor, :hidden => true %>
          </span>
          <span ng-if="!selecionarIconesSocialFacebook">
            <% valor = "Facebook" %>
            <%= f.text_field :social, :value => valor, :hidden => true %>
          </span>
          <span ng-if="!selecionarIconesSocialSkype">
            <% valor = "Skype" %>
            <%= f.text_field :social, :value => valor, :hidden => true %>
          </span>
          <span ng-if="!selecionarIconesSocialYoutube">
            <% valor = "Youtube" %>
            <%= f.text_field :social, :value => valor, :hidden => true %>
          </span>
          <span ng-if="!selecionarIconesSocialLinkedin">
            <% valor = "Linkedin" %>
            <%= f.text_field :social, :value => valor, :hidden => true %>
          </span>
          </br></br></br><hr> 
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/prospectos/_historicoContato.html.erb
<div ng-app="demo">
	<div ng-controller="ControllerHistoricoContato">
		<div ng-hide="esconderHistoricoContato">

      <!--<%= form_tag(historicoprospectos_path, :method => :get) do %>
        <%= text_field_tag 'search', nil, placeholder: 'Entre...' %>
        <%= submit_tag "search" %>
      <% end %>-->

      <%= form_for Historicoprospecto.new, :html => { :class => "form-horizontal historicoprospecto" } do |f|  %>
        <div ng-hide="esconderHistoricoContato">
          <div class="control-group">
            <div class="controls">  
              <div class="col-xs-10"><%= f.text_area :descricao, size: "50x5", :placeholder => "Descrição do contato: (o que aconteceu? Como foi? Quem atendeu?)", :class => 'form-control' %>
              </div>  
            </div>
          </div>
          </br></br></br></br></br> </br></br></br>
          <div class="col-xs-10">
            <div class="input-group">
              <span class="input-group-btn">
                <span style="background-color:#F24472" class="btn btn-primary" onclick="$(this).parent().find('input[type=file]').click();">Anexar</span>
                <%= f.file_field :anexo, :onchange => "$(this).parent().parent().find('.form-control').html($(this).val().split(/[\\|/]/).pop());", :style => "display: none;", :type => "file" %>
              </span>
              <span class="form-control"></span>
            </div> 
          </div> </br> </br></br>

          <div class="control-group">
            <div class="controls">  
              <div class="col-xs-4"><%= f.collection_select :situacao_id, Situacao.all, :id, :nome, {prompt: "Status"}, {class: "form-control"} %>
              </div>  
            </div>
          </div>
          <%= f.submit "Salvar", :class => 'btn btn-primary botaoSalvar' %>
        </div></br></br></br> 
      <% end %>
    </div>
	</div>
</div>

app/views/prospectos/_menu.html.erb
<div ng-app="demo">
	<div ng-controller="ControllerMenu">

		<p style="color:#a39d95" ng-click="esconderCadastroBasico = true" ng-show="!esconderCadastroBasico">CADASTRO BÁSICO <span ng-click="esconderCadastroBasico = true" ng-show="!esconderCadastroBasico" class="glyphicon glyphicon-minus alinhandoIcones coresIconesMenos"></span></p>

		<p style="color:#a39d95" ng-click="esconderCadastroBasico = false" ng-show="esconderCadastroBasico">CADASTRO BÁSICO <span ng-click="esconderCadastroBasico = false" ng-show="esconderCadastroBasico" class="glyphicon glyphicon-plus alinhandoIcones coresIconesMais"></span></p>
		
		<%= render :partial => 'cadastroBasico' %>

		<p style="color:#a39d95" ng-click="esconderHistoricoContato = true" ng-show="!esconderHistoricoContato">HISTÓRICO DE CONTATOS <span ng-click="esconderHistoricoContato = true" ng-show="!esconderHistoricoContato" class="glyphicon glyphicon-minus alinhandoIcones coresIconesMenos"></span></p>

      	<p style="color:#a39d95" ng-click="esconderHistoricoContato = false" ng-show="esconderHistoricoContato">HISTÓRICO DE CONTATOS <span size:"10px" ng-click="esconderHistoricoContato = false" ng-show="esconderHistoricoContato" class="glyphicon glyphicon-plus alinhandoIcones coresIconesMais"></span></p>

      	<%= render :partial => 'historicoContato' %>

		<p style="color:#a39d95" ng-click="esconderCadastroCompleto = true" ng-show="!esconderCadastroCompleto">CADASTRO COMPLETO <span ng-click="esconderCadastroCompleto = true" ng-show="!esconderCadastroCompleto" class="glyphicon glyphicon-minus alinhandoIcones coresIconesMenos"></span></p>

      	<p style="color:#a39d95" ng-click="esconderCadastroCompleto = false" ng-show="esconderCadastroCompleto">CADASTRO COMPLETO <span size:"10px" ng-click="esconderCadastroCompleto = false" ng-show="esconderCadastroCompleto" class="glyphicon glyphicon-plus alinhandoIcones coresIconesMais"></span></p>

		<h2 style="color:#f24472">USUÁRIOS</h2>

		<p style="color:#a39d95" ng-click="esconderCadastroUsuario = true" ng-show="!esconderCadastroUsuario">CADASTRO <span ng-click="esconderCadastroUsuario = true" ng-show="!esconderCadastroUsuario" class="glyphicon glyphicon-minus alinhandoIcones coresIconesMenos"></span></p>

		<p style="color:#a39d95" ng-click="esconderCadastroUsuario = false" ng-show="esconderCadastroUsuario">CADASTRO <span size:"10px" ng-click="esconderCadastroUsuario = false" ng-show="esconderCadastroUsuario" class="glyphicon glyphicon-plus alinhandoIcones coresIconesMais" ></span></p>

		<p style="color:#a39d95" ng-click="esconderFuncaoUsuario = true" ng-show="!esconderFuncaoUsuario">FUNÇÕES <span ng-click="esconderFuncaoUsuario = true" ng-show="!esconderFuncaoUsuario" class="glyphicon glyphicon-minus alinhandoIcones coresIconesMenos"></span></p>

		<p style="color:#a39d95" ng-click="esconderFuncaoUsuario = false" ng-show="esconderFuncaoUsuario">FUNÇÕES <span size:"10px" ng-click="esconderFuncaoUsuario = false" ng-show="esconderFuncaoUsuario" class="glyphicon glyphicon-plus alinhandoIcones coresIconesMais"></span></p>

		<p style="color:#a39d95" ng-click="esconderPermissaoUsuario = true" ng-show="!esconderPermissaoUsuario">PERMISSÕES <span ng-click="esconderPermissaoUsuario = true" ng-show="!esconderPermissaoUsuario" class="glyphicon glyphicon-minus alinhandoIcones coresIconesMenos"></span></p>

		<p style="color:#a39d95" ng-click="esconderPermissaoUsuario = false" ng-show="esconderPermissaoUsuario">PERMISSÕES <span size:"10px" ng-click="esconderPermissaoUsuario = false" ng-show="esconderPermissaoUsuario" class="glyphicon glyphicon-plus alinhandoIcones coresIconesMais"></span></p>

	</div>
</div>

app/views/prospectos/edit.html.erb
<%- model_class = Prospecto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'cadastroBasico' %>

app/views/prospectos/index.html.erb
<%- model_class = Prospecto -%>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<body>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:nome) %></th>
        <th><%= model_class.human_attribute_name(:empresa) %></th>
        <th><%= model_class.human_attribute_name(:telefone) %></th>
        <th><%= model_class.human_attribute_name(:email) %></th>
        <th><%= model_class.human_attribute_name(:cidade) %></th>
        <th><%= model_class.human_attribute_name(:estado) %></th>
        <th><%= model_class.human_attribute_name(:Criado_em) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>

    <tbody >

      <% @prospectos.each do |prospecto| %>
        <tr>
          <td><%= link_to prospecto.nome, prospecto_path(prospecto) %></td>
          <td><%= prospecto.empresa %></td>
          <td><%= prospecto.telefone %></td>
          <td><%= prospecto.email %></td>
          <td><%= prospecto.cidade %></td>
          <td><%= prospecto.estado.nome %></td>
          <td><%=l prospecto.created_at, :format => '%d/%B/%y' %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_prospecto_path(prospecto), :class => 'btn btn-default btn-xs' %>

            <%= link_to t('.destroy', :default => t("helpers.links.destroy")), prospecto_path(prospecto), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</body>

<%= link_to t('.new', :default => t("helpers.links.new")), new_prospecto_path, :class => 'btn btn-primary' %>

app/views/prospectos/index.pdf.erb
<%- model_class = Prospecto -%>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<body>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:nome) %></th>
        <th><%= model_class.human_attribute_name(:empresa) %></th>
        <th><%= model_class.human_attribute_name(:telefone) %></th>
        <th><%= model_class.human_attribute_name(:email) %></th>
        <th><%= model_class.human_attribute_name(:cidade) %></th>
        <th><%= model_class.human_attribute_name(:estado) %></th>
        <th><%= model_class.human_attribute_name(:Criado_em) %></th>
      </tr>
    </thead>

    <tbody >

      <% @prospectos.each do |prospecto| %>
        <tr>
          <td><%= link_to prospecto.nome, prospecto_path(prospecto) %></td>
          <td><%= prospecto.empresa %></td>
          <td><%= prospecto.telefone %></td>
          <td><%= prospecto.email %></td>
          <td><%= prospecto.cidade %></td>
          <td><%= prospecto.estado %></td>
          <td><%=l prospecto.created_at, :format => '%d/%m/%y' %></td>
          
        </tr>
      <% end %>
    </tbody>
  </table>
</body>

app/views/prospectos/new.html.erb
<script type='text/javascript'>
	(function(){
		if(window.localStorage){
			if( !localStorage.getItem('firstLoad')){
	      		localStorage[ 'firstLoad' ] = true;
	      	window.location.reload();
	    	}  
	    	else
	      		localStorage.removeItem('firstLoad');
	  	}
	})();
</script>

<div class="container">
	</br></br><h3 style="color:#f24472"><%= l Time.new, :format => '%d de %B' %></h3>
	<h4><%= current_usuario.nome %></h4>
	<h5><%= current_usuario.funcao %></h5>

	<h2 style="color:#f24472">PROSPECTO</h2>

	<%= render :partial => 'menu' %>
</div>

app/views/prospectos/show.html.erb
<%- model_class = Prospecto -%>

<div class="page-header">

  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>

</div>

<dl class="dl-horizontal">

  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>

  <dd><%= @prospecto.nome %></dd>

  <dt><strong><%= model_class.human_attribute_name(:empresa) %>:</strong></dt>

  <dd><%= @prospecto.empresa %></dd>

  <dt><strong><%= model_class.human_attribute_name(:telefone) %>:</strong></dt>

  <dd><%= @prospecto.telefone %></dd>

  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>

  <dd><%= @prospecto.email %></dd>

  <dt><strong><%= model_class.human_attribute_name(:cidade) %>:</strong></dt>

  <dd><%= @prospecto.cidade %></dd>

  <dt><strong><%= model_class.human_attribute_name(:estado) %>:</strong></dt>

  <dd><%= @prospecto.estado %></dd>

</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),

              prospectos_path, :class => 'btn btn-default'  %>

<%= link_to t('.edit', :default => t("helpers.links.edit")),

              edit_prospecto_path(@prospecto), :class => 'btn btn-default' %>

<%= link_to t('.destroy', :default => t("helpers.links.destroy")),

              prospecto_path(@prospecto),

              :method => 'delete',

              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },

              :class => 'btn btn-danger' %>

app/views/usuarios/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>